import React from 'react';
import { AILabel, AILabelContent, AILabelActions, Button, IconButton } from '@carbon/react';
import { View, FolderOpen, Folders } from '@carbon/icons-react';

export default {
  title: 'Components/AILabel',
  component: AILabel,
};

export const Default = () => (
  <div style={{ padding: '2rem' }}>
    <h3>AI Label - Default</h3>
    <p>
      This is a label with AI capabilities <AILabel />
    </p>
  </div>
);

export const WithPopover = () => (
  <div style={{ padding: '2rem' }}>
    <h3>AI Label with Popover Content</h3>
    <p>
      AI-generated content{' '}
      <AILabel>
        <AILabelContent>
          <div>
            <p style={{ marginBottom: '1rem' }}>
              This content was generated by AI. You can review and edit it.
            </p>
            <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)' }}>
              Model: GPT-4 | Confidence: 95%
            </p>
          </div>
        </AILabelContent>
        <AILabelActions>
          <IconButton kind="ghost" label="View details">
            <View />
          </IconButton>
          <IconButton kind="ghost" label="Open">
            <FolderOpen />
          </IconButton>
        </AILabelActions>
      </AILabel>
    </p>
  </div>
);

export const Sizes = () => (
  <div style={{ padding: '2rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
    <h3>AI Label Sizes</h3>
    <div style={{ display: 'flex', gap: '1rem', alignItems: 'center' }}>
      <span>Mini: <AILabel size="mini" /></span>
      <span>2XS: <AILabel size="2xs" /></span>
      <span>XS: <AILabel size="xs" /></span>
      <span>Small: <AILabel size="sm" /></span>
      <span>Medium: <AILabel size="md" /></span>
      <span>Large: <AILabel size="lg" /></span>
      <span>XL: <AILabel size="xl" /></span>
    </div>
  </div>
);
